package com.example.compose
import androidx.compose.ui.graphics.Color


val md_theme_light_primary = Color(0xFF2954cf)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFdbe1ff)
val md_theme_light_onPrimaryContainer = Color(0xFF001453)
val md_theme_light_secondary = Color(0xFF595d71)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFdee1f9)
val md_theme_light_onSecondaryContainer = Color(0xFF161b2c)
val md_theme_light_tertiary = Color(0xFF74546f)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd7f7)
val md_theme_light_onTertiaryContainer = Color(0xFF2c122a)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfefbff)
val md_theme_light_onBackground = Color(0xFF1b1b1f)
val md_theme_light_surface = Color(0xFFfefbff)
val md_theme_light_onSurface = Color(0xFF1b1b1f)
val md_theme_light_surfaceVariant = Color(0xFFe2e1ec)
val md_theme_light_onSurfaceVariant = Color(0xFF45464e)
val md_theme_light_outline = Color(0xFF76767f)
val md_theme_light_inverseOnSurface = Color(0xFFf3f0f5)
val md_theme_light_inverseSurface = Color(0xFF303033)
val md_theme_light_inversePrimary = Color(0xFFb4c4ff)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFb4c4ff)
val md_theme_dark_onPrimary = Color(0xFF002683)
val md_theme_dark_primaryContainer = Color(0xFF0039b6)
val md_theme_dark_onPrimaryContainer = Color(0xFFdbe1ff)
val md_theme_dark_secondary = Color(0xFF618AFF)
val md_theme_dark_onSecondary = Color(0xFF2b2f42)
val md_theme_dark_secondaryContainer = Color(0xff49C998)
val md_theme_dark_onSecondaryContainer = Color(0xFFdee1f9)
val md_theme_dark_tertiary = Color(0xFFFFFFFF)
val md_theme_dark_onTertiary = Color(0xFF000000)
val md_theme_dark_tertiaryContainer = Color(0xFF5b3d57)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd7f7)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1A242E)
val md_theme_dark_onBackground = Color(0xFF6B7A8D)
val md_theme_dark_surface = Color(0xFF222e3a)
val md_theme_dark_onSurface = Color(0xFFe4e2e6)
val md_theme_dark_surfaceVariant = Color(0xFF45464e)
val md_theme_dark_onSurfaceVariant = Color(0xFF151e27)
val md_theme_dark_outline = Color(0xFF434d59)
val md_theme_dark_inverseOnSurface = Color(0xFF1b1b1f)
val md_theme_dark_inverseSurface = Color(0xFFe4e2e6)
val md_theme_dark_inversePrimary = Color(0xFF222e3a)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_purple = Color(0xFFA986F9)




val seed = Color(0xFF3961dc)
val error = Color(0xFFba1b1b)